# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_chat_api:
  path: /chat-api
  controller: App\Controller\ChatController::ask
  methods: [POST]
